# Calculations for HW4

In [1]:
import numpy as np
from CenterOfMass import CenterOfMass

## Q6, part 1

In [2]:
#MW
MW_COM = CenterOfMass('MW_000.txt', 2)
MW_COM_p = MW_COM.COM_P(0.1)
print(MW_COM_p)
MW_COM_v = MW_COM.COM_V(MW_COM_p[0], MW_COM_p[1], MW_COM_p[2])
print(MW_COM_v)

CHANGE =  0.22978104414074885
maxR 11.020481333398111
CHANGE =  0.47043363423848117
maxR 5.5102406666990555
CHANGE =  0.20089037674475652
maxR 2.7551203333495278
CHANGE =  0.030187165196947863
maxR 1.3775601666747639
[-2.07  2.95 -1.45] kpc
[ 1.  6. -1.] km / s


In [3]:
#M31
M31_COM = CenterOfMass('M31_000.txt', 2)
M31_COM_p = M31_COM.COM_P(0.1)
print(M31_COM_p)
M31_COM_v = M31_COM.COM_V(M31_COM_p[0], M31_COM_p[1], M31_COM_p[2])
print(M31_COM_v)

CHANGE =  0.04459429679900495
maxR 16.68229943877858
[-377.66  611.43 -284.64] kpc
[ 73. -72.  49.] km / s


In [4]:
#M33
M33_COM = CenterOfMass('M33_000.txt', 2)
M33_COM_p = M33_COM.COM_P(0.1)
print(M33_COM_p)
M33_COM_v = M33_COM.COM_V(M33_COM_p[0], M33_COM_p[1], M33_COM_p[2])
print(M33_COM_v)

CHANGE =  0.01308865872044862
maxR 3.9330197268235163
[-476.22  491.44 -412.4 ] kpc
[ 44. 102. 142.] km / s


## Q6 part 2

In [11]:
rel_sep_MW_M31 = np.sqrt(np.sum((M31_COM_p - MW_COM_p)**2))
print(np.round(rel_sep_MW_M31, 3))

769.098 kpc


In [12]:
rel_vel_MW_M31 = np.sqrt(np.sum((M31_COM_v - MW_COM_v)**2))
print(np.round(rel_vel_MW_M31, 3))

117.337 km / s


## Q6 part 3

In [13]:
rel_sep_M33_M31 = np.sqrt(np.sum((M31_COM_p - M33_COM_p)**2))
print(np.round(rel_sep_M33_M31, 3))

201.083 kpc


In [15]:
rel_vel_M33_M31 = np.sqrt(np.sum((M31_COM_v - M33_COM_v)**2))
print(np.round(rel_vel_M33_M31, 3))

199.414 km / s


## Q6 part 4

To avoid outlying stars.